config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#top"

  resources :books, only: [:edit, :index, :show, :create, :destroy, :update]
  resources :users, only: [:edit, :index, :show, :update]

  get "/home/about" => "home#about", as: "about"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  #has_one_attached :title, :body
  belongs_to :user

  validates :title, presence: true, length: { maximum: 200 }
  validates :body, presence: true, length: { maximum: 200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  has_one_attached :profile_image
  
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)

  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @books = Book.all
    @user = @book.user
    flash[:notice] = "You have created book successfully."
  end

  def edit
    
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

   def is_matching_login_user
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @newbook = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @user = current_user
    @users = User.all
    @newbook = Book.new
    @books = current_user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to users_path
    end
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 ml-md-auto">
    <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

    <h3>Editing Book</h3>
    <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
    <h5>Title</h5>
    <%= f.text_field :title %>

	  <div class="from-group">
      <h5>Opinion</h5>
      <%= f.text_area :body %>
    </div>
    <div class="from-group">
    <%= f.submit 'Update Book', class: "btn btn-sm btn-success" %>
    </div>

    <span>
      <%= link_to "Show", book_path(@book.id) %>
    </span>

    <span>
      <%= link_to "Back", books_path %>
    </span>

    <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
<% end %>
<%= render 'users/list', user: @user,book: @book %>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>

app/views/books/show.html.erb
<%= render 'users/list', user: @user,book: @newbook %>
  <div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
    <table class="table table-hover table-inverse">
      <tbody>
        <tr>
          <th><%= link_to user_path(current_user.id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %>
              <% end %>
          </th>
          <th><%= link_to @book.user.name, user_path(@book.id) %></th>
          <th><%= link_to @book.title, book_path %></th>
          <th><%= @book.body %></th>
          <% if @book.user == current_user %>
            <th><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></th>
            <th><%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "Are you sure?"%></th>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
 

app/views/home/about.html.erb
<div class = "container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to</h1>
    <i class="fa-solid fa-book"></i>
    <h1 class="px-3 mx-auto">Bookers!</h1>
  </div>
</div>

app/views/home/top.html.erb
<div class = "container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to</h1>
    <i class="fa-solid fa-book"></i>
    <h1 class="px-3 mx-auto">Bookers!</h1>
  </div>
</div>

<div class = "container">
  <div class="row">
    <div class="mx-auto col-6">
      <p>In 
        <i class="fa-solid fa-book"></i>
        Bookers,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

    <%= form_with model: @user, url: user_session_path, local: true do |f| %>
    <div class="input-group-prepend">
      <span class="input-group-text, btn btn-lg btn-block btn-info mt-5" aria-hidden="true"><%= link_to "Log in", new_user_session_path %></span>
    </div>
    <div>
      <span class="input-group-text, btn btn-lg btn-block btn btn-success mt-5" aria-hidden="true"><%= link_to "Sign up", new_user_registration_path %></span>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class = "container">
   <div class="row">
    <div class="mx-auto col-6">

        <h2>welcome to Bookers !!</h2>
        <p>In 
          <i class="fa-solid fa-book"></i>
          Bookers,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>

    <%= form_with model: @user, url: user_session_path, local: true do |f| %>
    <div class="input-group-prepend">
      <span class="input-group-text, btn btn-lg btn-block btn-info mt-5" aria-hidden="true"><%= link_to "Log in", new_user_session_path %></span>
    </div>
    <div>
      <span class="input-group-text, btn btn-lg btn-block btn btn-success mt-5" aria-hidden="true"><%= link_to "Sign up", new_user_registration_path %></span>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta charset="UTF-8" />
<script src="https://kit.fontawesome.com/f9c8ebb418.js" crossorigin="anonymous"></script>

<html>
  <head>
    <div class="container">
      <div class="row justify-content-start">
        <title>Bookers2</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      </div>
    </div>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <tr>
                <% if user_signed_in? %>
                  <%= link_to user_path(current_user.id) do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                  <%= link_to users_path do %>
                    <i class="fa-solid fa-users"></i>Users
                  <% end %>
                  <%= link_to books_path do %>
                    <i class="fa-solid fa-book-open"></i>Books
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete do%>
                    <i class="fa-solid fa-sign-out-alt"></i>Log out
                  <% end %>
                <% else %>
                  <%= link_to root_path do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                  <%= link_to about_path do %>
                    <i class="fa-solid fa-link"></i>About
                  <% end %>
                  <%= link_to new_user_registration_path do %>
                    <i class="fa-solid fa-user-plus"></i>Sign up
                  <% end %>
                  <%= link_to new_user_session_path do %>
                    <i class="fa-solid fa-sign-in-alt"></i>Log in
                  <% end %>
                <% end %>
              </tr>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div>
        <%= flash[:notice] %>
      </div>
      <div class="container px-5 px-sm-0">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>

  </body>

    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>


</html>

app/views/users/_list.html.erb
<div class="col-md-3">

  <h2>User info</h2>
  <table class="table table-striped">
    <%= image_tag 'no_image', size: "100x100" %>
      <tr>
        <th>name</th>
        <th><%=user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%=user.introduction %></th>
      </tr>
  </table>
  <%= link_to edit_user_path(user.id), :class => 'btn btn-outline-secondary btn-block' do %>
    <i class="fa-solid fa-user-cog"></i>
  <% end %>

  <%= form_with model: book, local:true, method: :post do |f| %>


  <h3>New book</h3>

  <h5>Title</h5>
    <%= f.text_field :title %>

  <h5>Opinion</h5>
    <%= f.text_area :body %>

  <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>


</div>

app/views/users/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
  <% if @user.errors.any? %>
    <%= @user.errors.count %>errors prohibited this book from being saved:>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

<%= form_with model: @user, url: user_path do |f| %>
  <div>
    <label for="inputName">Name</label>
  </div>
  <div>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  </div>
  <div>
    <label for="inputImage">Image</label>
  </div>
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>

  <div>
    <label for="inputImage">Introduction</label>
  </div>
  <div>
    <%= f.text_area :introduction %>
  </div>
  <%= f.submit "Update User", class: "btn btn-secondary" %>

<% end %>
</div>

app/views/users/index.html.erb
<%= render 'users/list', user: @user,book: @newbook %>
  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(100, 100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/users/show.html.erb
<%= render 'users/list', user: @user,book: @newbook %>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>